import "./globals.css";
import type { Metadata } from "next";
import Poppins from "next/font/google"
import Link from "next/link";
import { buttonVariants } from "./components/ui/button";


export const metadata: Metadata = {
  title: "Quick",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <nav className="flex justify-end p-4 ">
        
            <Link className={buttonVariants({ variant: "outline" })} href="/createpoll" >Create poll</Link>
            <Link className={buttonVariants({ variant: "outline" })} href="/viewpoll">View Polls</Link>
          
        </nav>
        {children}
      </body>
    </html>
  );
}